### ISSUE TITLE
numpy fails to compile on Linuxbrew --with-openblas

### ISSUE THREAD

**Issue by davydden** [Homebrew/homebrew-python#209]
`numpy` seems to fail to compile in Linuxbrew (Ubuntu 14.04):
```
$ brew install numpy --with-openblas
...
python setup.py build --fcompiler=gnu95 install --prefix=/home/davydden/.linuxbrew/Cellar/numpy/1.9.2
/tmp/numpy-aOmGFe/numpy-1.9.2/numpy/core/blasdot/python_xerbla.c:45: undefined reference to `PyExc_ValueError'
/tmp/numpy-aOmGFe/numpy-1.9.2/numpy/core/blasdot/python_xerbla.c:45: undefined reference to `PyErr_SetString'
/tmp/numpy-aOmGFe/numpy-1.9.2/numpy/core/blasdot/python_xerbla.c:47: undefined reference to `PyGILState_Release'
collect2: error: ld returned 1 exit status
error: Command "/home/davydden/.linuxbrew/bin/gfortran -Wall -g -L/home/davydden/.linuxbrew/lib -Wl,-rpath,/home/davydden/.linuxbrew/lib build/temp.linux-x86_64-2.7/numpy/core/blasdot/_dotblas.o build/temp.linux-x86_64-2.7/numpy/core/blasdot/python_xerbla.o build/temp.linux-x86_64-2.7/numpy/core/blasdot/apple_sgemv_patch.o -L/home/davydden/.linuxbrew/opt/openblas/lib -Lbuild/temp.linux-x86_64-2.7 -lopenblas -lopenblas -lgfortran -o build/lib.linux-x86_64-2.7/numpy/core/_dotblas.so" failed with exit status 1
```

**Comment by tdsmith** [comment]
I'll consider PRs but I don't plan to investigate this. Is this a numpy bug? It looks like it needs -lpython and isn't passing it.

**Comment by davydden** [comment]
adding
```
ENV["LDFLAGS"] = "-lpython2.7"
```
brought it a bit further, i think:
```
/usr/bin/ld: /usr/lib/debug/usr/lib/x86_64-linux-gnu/crt1.o(.debug_line): relocation 0 has invalid symbol index 2
/usr/lib/x86_64-linux-gnu/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status
error: Command "/home/davydden/.linuxbrew/bin/gfortran -Wall -g -lpython2.7 build/temp.linux-x86_64-2.7/numpy/core/blasdot/_dotblas.o build/temp.linux-x86_64-2.7/numpy/core/blasdot/python_xerbla.o build/temp.linux-x86_64-2.7/numpy/core/blasdot/apple_sgemv_patch.o -L/home/davydden/.linuxbrew/opt/openblas/lib -Lbuild/temp.linux-x86_64-2.7 -lopenblas -lopenblas -lgfortran -o build/lib.linux-x86_64-2.7/numpy/core/_dotblas.so" failed with exit status 1
```
p.s. i don't use `python`  nor `numpy`

**Comment by davydden** [comment]
and there are many others :( i don't think i will look at it...

**Comment by tdsmith** [comment]
Can reproduce on Ubuntu 14.04.2. numpy builds correctly with Ubuntu's ATLAS but not with openblas.

Logs: https://gist.github.com/7bdc4cf5777cda7fa5c7

**Comment by tdsmith** [comment]
Upstream issue: https://github.com/numpy/numpy/issues/4203
